// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PilotageFinancier.Infrastructure;

#nullable disable

namespace PilotageFinancier.Infrastructure.Migrations
{
    [DbContext(typeof(PilotageDbContext))]
    partial class PilotageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("PilotageFinancier.Domain.BudgetVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePCGE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("TEXT");

                    b.Property<int>("Exercice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantVote")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodePCGE", "Exercice", "DateValidite");

                    b.ToTable("BudgetsVotes");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.EcritureBrute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantDebit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("TenantId", "ImportBatchId");

                    b.ToTable("EcrituresBrutes");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.EcritureNormalisee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePCGE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantDebit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceBatchId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Date");

                    b.ToTable("EcrituresNormalisees");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImporteLe")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbLignes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.MappingCompte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeClientSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePCGENormalise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CodeClientSource")
                        .IsUnique();

                    b.ToTable("Mappings");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.SerieAgregee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePCGE")
                        .HasColumnType("TEXT");

                    b.Property<int>("Granularite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Periode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeSerie")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TypeSerie", "Granularite", "Periode");

                    b.ToTable("SeriesAgregees");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.EcritureBrute", b =>
                {
                    b.HasOne("PilotageFinancier.Domain.ImportBatch", "ImportBatch")
                        .WithMany("Lignes")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.ImportBatch", b =>
                {
                    b.HasOne("PilotageFinancier.Domain.Tenant", null)
                        .WithMany("Imports")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PilotageFinancier.Domain.MappingCompte", b =>
                {
                    b.HasOne("PilotageFinancier.Domain.Tenant", null)
                        .WithMany("Mappings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PilotageFinancier.Domain.ImportBatch", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("PilotageFinancier.Domain.Tenant", b =>
                {
                    b.Navigation("Imports");

                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
